version: "3"

volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: ./grav-data
      o: bind

services:
  grav:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - grav-data:/var/www/grav
    restart: always
